### ISSUE TITLE
Help with template

### ISSUE THREAD

**Issue by D4llo** [JamieMagee/aur-packages-template#27]
Hello,

I am trying to submit a package to the AUR with this template. Here is my repository https://github.com/D4llo/surfshark-yac/

Both GH actions fail. I think that I missed something but I am not sure what. Do you have any idea?

Publish action: https://github.com/D4llo/surfshark-yac/actions/runs/7702075403

![image](https://github.com/JamieMagee/aur-packages-template/assets/131776117/a429f919-1db2-44d3-81b1-05f6a1b9df15)

I tested my passpharse locally with `ssh-keygen -y -P "<my_passphrase>" -f ~/.ssh/id_ed25519` and it works as expected

Updpkgsums action: https://github.com/D4llo/surfshark-yac/actions/workflows/updpkgsums.yml

![image](https://github.com/JamieMagee/aur-packages-template/assets/131776117/29824ea9-3cee-4a6f-9bd2-89273c0d31d9)

Note that this my first time submitting something to the AUR.

My pub key is on my AUR account:
![image](https://github.com/JamieMagee/aur-packages/assets/131776117/b7ccb407-6baf-4c86-8349-f4e7dc82b102)

My passphrase, my login and my mail are set as Repository secrets

![image](https://github.com/JamieMagee/aur-packages/assets/131776117/070256f0-718c-4c58-a350-8e8a4d9457e4)

(maybe it should be Environment secrets?)

Cheers,

source:
- https://github.com/JamieMagee/aur-packages-template/
- https://github.com/JamieMagee/aur-packages/
- https://jamiemagee.co.uk/blog/maintaining-aur-packages-with-renovate/

**Comment by JamieMagee** [comment]
Yeah, you need to use an SSH private key without a passphrase. Otherwise GitHub Actions is not able to unlock it.

Everything else looks correct.

**Comment by D4llo** [comment]
Alright I am going to try that. Thanks a lot for your work and the quick comment!

**Comment by D4llo** [comment]
It worked. kinda. I have a new issue later on. Should I keep posting over here or should I create a new issue?

This is about this action
https://github.com/D4llo/surfshark-yac/actions/runs/7716321502/job/21032834330

![image](https://github.com/JamieMagee/aur-packages-template/assets/131776117/30571aa0-732a-46bc-9f65-ad53a2bc35ba)

Edit: I think I got it. Still working on it

**Comment by JamieMagee** [comment]
This issue is fine.

What's the new problem?

**Comment by D4llo** [comment]
I dont think that it is related to the template. I am not sure.

I am trying to push an AUR package based on a deb package. The script is looking to download the deb file through curl but failed.

I can wget the .deb in local

![image](https://github.com/JamieMagee/aur-packages-template/assets/131776117/75db452a-0d83-47e1-b5bd-1e13931466df)

Here is the log of the GitHub Actions

![image](https://github.com/JamieMagee/aur-packages-template/assets/131776117/98fb19c7-4613-46de-ab13-ff85b9a7ae67)

link: https://github.com/D4llo/surfshark-yac/actions/runs/7717047680/job/21035250047

There is another issue about the missing `pacman-key --init`. Could it be related?

**Comment by D4llo** [comment]
Just saw that the url path seems to have change. Let's remove the subpath `/surfshark/`

Edit: OH BOY https://github.com/D4llo/surfshark-yac/actions/runs/7718706385/job/21040539081?pr=7

Edit 2: Ok the publish just started https://github.com/D4llo/surfshark-yac/actions/runs/7718728168/job/21040599267

Edit 3: and it failed `==> ERROR: install file (surfshark-yac.install) does not exist or is not a regular file.` Let's dig. https://github.com/D4llo/surfshark-yac/actions/runs/7718728168/job/21040599267#step:5:83

```
Cloning AUR package into /tmp/local-repo
  Cloning into '/tmp/local-repo'...
  POST git-upload-pack (175 bytes)
  warning: You appear to have cloned an empty repository.
```

Why this repository is empty? Should I init it in some way? Maybe in the AUR side?

**Comment by D4llo** [comment]
What is a regular file? Because indeed the surfshark-yac.install is not a common file. Maybe we are expected a specific name or something like that. How to include it properly?

**Comment by D4llo** [comment]
Ok I am digging the "not included" idea. Let's follow this line:

https://github.com/D4llo/surfshark-yac/blob/918711c841add120fed9fff990fc8f5e12c22347/.github/workflows/updpkgsums.yml#L39

```
- name: Commit
        if: ${{ env.pkgbuild != '' }}
        uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5.0.0
        with:
          file_pattern: '*/PKGBUILD */.SRCINFO'
```

I think that I should edit the file_pattern to include everything or add a argument for my file.

Edit: as per the [stefanzweifel/git-auto-commit-action's documentation](https://github.com/stefanzweifel/git-auto-commit-action/blob/12f68633e45c72459cd040c868605f2471c7f63b/README.md?plain=1#L433). It should work.
```
`file_pattern` is used both for `git-status` and `git-add` in this Action. `git-add` will throw a fatal error, if for example, you use a file pattern like `*.js *.ts` but no `*.ts` files exist in your projects' repository.
```

**Comment by D4llo** [comment]
Failed again 
![image](https://github.com/JamieMagee/aur-packages-template/assets/131776117/adfa955d-dc4d-495b-8fc0-fbb93fd64942)

But I think I am on something

Edit: nevermind it is "*/" and not "./" LMAO

**Comment by D4llo** [comment]
Still failing...
![image](https://github.com/JamieMagee/aur-packages-template/assets/131776117/03fc3d33-e716-42a9-8aba-bb055baa9299)

https://github.com/D4llo/surfshark-yac/actions/runs/7725179403/job/21058847363#step:5:92

FYI this is the pattern now 
![image](https://github.com/JamieMagee/aur-packages-template/assets/131776117/25e60f81-9cba-46ea-9bc3-108056185e63)


I am a bit puzzled...

**Comment by JamieMagee** [comment]
I think it's because it's looking for `surfshark-yac.install` in the root of the directory, but it's in the `surfshark-yac` sub-directory. Can you try set [`working-directory`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsworking-directory) for that step?

**Comment by D4llo** [comment]
Not sure how to do that. Should I do this in `.github/workflows/publish.yml`?

```yaml
   - name: Publish package
        working-directory: ./surfshark-yac
        uses: KSXGitHub/github-actions-deploy-aur@063daf78a56662642bb00049ce78425ff6d0fad7 # v2.7.0
        if: ${{ env.pkgbuild != '' }}
        with:
          pkgname: ${{ env.pkgbuild }}
          pkgbuild: ${{ env.pkgbuild }}/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
```

or during the packaging  in `updpkgsums.yml`?

```yaml
      - name: Commit
        working-directory: ./surfshark-yac
        if: ${{ env.pkgbuild != '' }}
        uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5.0.0
        with:
          file_pattern: '*/PKGBUILD */.SRCINFO */surfshark-yac.install */.gitignore'
```
https://github.com/D4llo/surfshark-yac/blob/35782c6114fdbf212dac4cc008f9641a9260f419/.github/workflows/publish.yml#L26

https://github.com/D4llo/surfshark-yac/blob/35782c6114fdbf212dac4cc008f9641a9260f419/.github/workflows/updpkgsums.yml#L35C1-L39C85
